### ISSUE TITLE
Unable to connect to settings server

### ISSUE THREAD

**Issue by linuxgoose** [nathaneltitane/dextop#50]
Hi - I've followed the instructions on the readme and it appears to trigger the x11 session, but the GUI throws the below error "Unable to connect to settings server"?

![Screenshot_20250311-214904_1.png](https://github.com/user-attachments/assets/9e76f541-18d8-44c3-b162-5fbebde6a1ce)

**Comment by nathaneltitane** [comment]
Interesting... steps to reproduce? never encountered this one

**Comment by linuxgoose** [comment]
Using a Fairphone5

- Termux, Termux x11, Termux:API installed
- Ensured fresh copy of Termux (cleared all storage and cache)
- Open Termux
- echo 'Home' > .storage
- curl -s -L run.dxtp.app > dextop && bash dextop
- I then get the "Dextop setup complete" after the automatic installs
- Type "container-session -u termux" which starts the included screenshot above, but I do see a flash of a client.conf not found? But it goes away then starts

![Screenshot_20250312-080039_1.png](https://github.com/user-attachments/assets/4e493aaf-cd75-4f49-bec8-80e99e2b0441)

**Comment by Elryth** [comment]
Same issue here.
Galaxy S24
Otherwise exactly as described by linuxgoose. Same errors with pulse/client.conf and 'unable to contact settings server'

**Comment by nathaneltitane** [comment]
confirmed - looking into this now - I have a clue as to what this may be. Stay tuned.

**Comment by nathaneltitane** [comment]
clean install on Galaxy Tab S7+ - PASS

**Comment by nathaneltitane** [comment]
settings server bug/error on container side due to unknown systemd requirement - investigating.

**Comment by nathaneltitane** [comment]
unknown image update leading to anomalous change in group entries - prevents packages from configuring and finishing install on container side.

**Comment by nathaneltitane** [comment]
offending item located at container-image:image_groups - disabled - container packages seem to be installing normally

**Comment by nathaneltitane** [comment]
fixed

**Comment by Elryth** [comment]
I uninstalled termux and started from scratch. Still getting the same error. Is there something else I should be doing to get a fresh install?

**Comment by linuxgoose** [comment]
> I uninstalled termux and started from scratch. Still getting the same error. Is there something else I should be doing to get a fresh install?

Likewise... Still the same error. The install appeared to go more smoothly overall though with less errors, however. The pulse audio one is for sure gone.

**Comment by nathaneltitane** [comment]
i really am sorry this isnt working. I've looked into what i thought was the problem and did a full Termus application storage and data clear on both my devices before running the updated setup again.

Both my devices install Dextop in its entirety now and i am able to use the Termux side and the Debian container side independanty and without issues (Minus an xkb warning on login)

Can you elaborate on your devices? Processor architecture, available storage?

Do you run the setup on LTE or on Wifi?

How good is the connection?

**Comment by nathaneltitane** [comment]
> > I uninstalled termux and started from scratch. Still getting the same error. Is there something else I should be doing to get a fresh install?
> 
> Likewise... Still the same error. The install appeared to go more smoothly overall though with less errors, however. The pulse audio one is for sure gone.

You need to go into the app settings and wip the termux data clean

**Comment by linuxgoose** [comment]
> > > I uninstalled termux and started from scratch. Still getting the same error. Is there something else I should be doing to get a fresh install?
> > 
> > 
> > Likewise... Still the same error. The install appeared to go more smoothly overall though with less errors, however. The pulse audio one is for sure gone.
> 
> You need to go into the app settings and wip the termux data clean

Yes, prior to retrying I cleared the cache and storage for all Termux apps.

**Comment by linuxgoose** [comment]
> i really am sorry this isnt working. I've looked into what i thought was the problem and did a full Termus application storage and data clear on both my devices before running the updated setup again.
> 
> Both my devices install Dextop in its entirety now and i am able to use the Termux side and the Debian container side independanty and without issues (Minus an xkb warning on login)
> 
> Can you elaborate on your devices? Processor architecture, available storage?
> 
> Do you run the setup on LTE or on Wifi?
> 
> How good is the connection?

I have tried this on WiFi (reliable connection with on average 30mbps down speed. The device is a Fairphone 5 with 8GB RAM, 65GB free storage and a 64bit Qualcomm QCM6490 processor.

**Comment by nathaneltitane** [comment]
> > i really am sorry this isnt working. I've looked into what i thought was the problem and did a full Termus application storage and data clear on both my devices before running the updated setup again.
> > 
> > Both my devices install Dextop in its entirety now and i am able to use the Termux side and the Debian container side independanty and without issues (Minus an xkb warning on login)
> > 
> > Can you elaborate on your devices? Processor architecture, available storage?
> > 
> > Do you run the setup on LTE or on Wifi?
> > 
> > How good is the connection?
> 
> I have tried this on WiFi (reliable connection with on average 30mbps down speed. The device is a Fairphone 5 with 8GB RAM, 65GB free storage and a 64bit Qualcomm QCM6490 processor.

i will need you to run 'container-session -x' to stop the display server and kill termux-x11

then, restart it manuall using 'container-session -o'

if the error message persists, please show me the output of the 'top' command to see what runs and what fails to. i will compare it to my fresh installation.

can you also run 'startxfce4' and see if the DE starts up at all manually?

thanks

**Comment by Elryth** [comment]
At least on my end this has been solved by using termux version 0.119.0-beta.1 despite the installation comparability warnings. The error persists with the most recent play store termux version 2025.01.18

Thanks!

**Comment by nathaneltitane** [comment]
> At least on my end this has been solved by using termux version 0.119.0-beta.1 despite the installation comparability warnings. The error persists with the most recent play store termux version 2025.01.18
> 
> Thanks!

Plat Stor Termux packages have been deprecated since Nov. 2020!

THIS IS MARKED IN BOLD IN THE README REQUIREMENT SECTION!

![Image](https://github.com/user-attachments/assets/32b71631-3185-46d7-80c5-456e117c46b3)

Glad to know the issue has been resolved.

**Comment by nathaneltitane** [comment]
Invalid bug : user installed deprecated Termux packages from play store.

**Comment by Elryth** [comment]
Thanks, I see that now. Probably worth putting it in the TlDr section as that's the first section with installation instructions. Also how/why is the play store version deprecated when it is showing a more recent update than the git link?

**Comment by nathaneltitane** [comment]
> Thanks, I see that now. Probably worth putting it in the TlDr section as that's the first section with installation instructions. Also how/why is the play store version deprecated when it is showing a more recent update than the git link?

Will do.

The original developer abandonned the project and the community took over. Google does not let anyone but the original developer manage the account where it is loaded.... we have to do with it unfortunately.

**Comment by Elryth** [comment]
Wow... that's really annoying by Google. I really appreciate your work!

**Comment by nathaneltitane** [comment]
> Wow... that's really annoying by Google. I really appreciate your work!

Yeah, google is becoming a real pain to work with.

I appreciate it and thank you for supportung my work by using it! ❤️

Please spread the word, it would make me happy to grow the project's user base!🫡

**Comment by nathaneltitane** [comment]
> Thanks, I see that now. Probably worth putting it in the TlDr section as that's the first section with installation instructions. Also how/why is the play store version deprecated when it is showing a more recent update than the git link?

To be fair, the TL;DR does mention which Termux and where to find them (urls included) - I will make it explicit to not use Google Play.

**Comment by linuxgoose** [comment]
Can confirm as well that the latest BETA version (0.119 beta 1) of Termux is working for me now as well. The Latest stable release (0.118.1) from the repo was not.

Cheers! Appreciate the work you're doing.
